### ISSUE TITLE
Implementation tracker: Table parsing

### ISSUE THREAD

**Issue by halvko** [adamAndMath/RandomLoot#2]
# Implementation Tracker
- [ ] General file syntax parsing
- [ ] Type support
    - [ ] bool: Boolean value allowing (y,n), (t,f), (yes,no), (true,false) and (1,0)
    - [ ] string: Text sequences of any size
    - [ ] float: Decimal number
    - [ ] int: Whole number
    - [ ] coin: Formated whole number, representing the value as the appropriate coins
    - [ ] ufloat, uint, ucoin: Unsigned versions of the numeric types
    - [ ] file|path: Boolean value representing whether the touple contains a member of the file
